# Generated by Django 5.1.1 on 2025-07-05 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='horario_preferido',
            field=models.CharField(choices=[('manana', 'Mañana (8:00 AM - 12:00 PM)'), ('tarde', 'Tarde (1:00 PM - 6:00 PM)'), ('noche', 'Noche (6:00 PM - 9:00 PM)'), ('flexible', 'Horario flexible')], default='tarde', max_length=20),
        ),
        migrations.AddField(
            model_name='servicio',
            name='urgencia',
            field=models.CharField(choices=[('baja', 'Baja - Puede esperar'), ('media', 'Media - En los próximos días'), ('alta', 'Alta - Lo antes posible')], default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('Plomería', 'Plomería'), ('Electricidad', 'Electricidad'), ('Jardinería', 'Jardinería'), ('Limpieza', 'Limpieza'), ('Carpintería', 'Carpintería'), ('Pintura', 'Pintura'), ('Albañilería', 'Albañilería'), ('Mecánica', 'Mecánica'), ('Tecnología', 'Tecnología'), ('Otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia bancaria'), ('Nequi', 'Nequi'), ('Daviplata', 'Daviplata'), ('Otro', 'Otro método')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='ubicacion',
            field=models.CharField(max_length=200),
        ),
    ]
